baseURL = "https://minvws.github.io/gfmodules-technische-documentatie"
locale = "nl"
title = "Generieke Functies Technische Documentatie"
theme = "gfmodules"
disableKinds = ["taxonomy", "term"]

[params]
  subtitle = "Generieke Functies"
  environment = "Proeftuin"
  contact_email = "helpdesk@irealisatie.nl"

[[menus.main]]
  name = "Overzicht"
  url = "/"
  weight = 1
[[menus.main]]
  name = "Services"
  url = "/services/"
  weight = 2
[[menus.main]]
  name = "Integratie"
  url = "/integration/"
  weight = 3
